#!/usr/bin/env bash

checkroot () {
	if [[ "$(whoami)" != root ]] ; then
		echo "You must be root to perform this operation!"
		exit 1
	fi
}

sync_repos_n_overlays () {
	emerge --sync
}

sync_portage_config () {
	pushd /opt/argentwork-build > /dev/null 2>&1
	echo ">>> Syncing 'portage config' into '/etc/portage'..."
	echo "/usr/bin/git pull"
	git pull
	echo "=== Sync completed for 'portage config'"
	popd > /dev/null 2>&1
}

main () {
	if checkroot ; then
		sync_repos_n_overlays
		sync_portage_config
	fi
}

main
