#!/usr/bin/env bash

source /usr/lib/epkg/libepkg

checkroot
checksystemmode

action=$1
shift

case "$action" in
	install)
		checksync
		emerge -av "$@"
		;;
	remove)
		checksync
		emerge --depclean -av "$@"
		;;
	backuppkg)
		backuppkg "$@"
		;;
	forceremove)
		checksync
		emerge --unmerge -av "$@"
		;;
	clean)
		checksync
		emerge --depclean -av
		;;
	cleanoutdated)
		cleanoutdated
		;;
	cleanlocalpkg)
		cleanlocalpkg
		;;
	upgrade)
		checksync
		emerge -uDvaN --with-bdeps=y @system @world "$@"
		;;
	autoinstall)
		argentsync
		emerge -v "$@"
		;;
	autoremove)
		argentsync
		emerge --depclean -v "$@"
		;;
        recompilepkg)
		argentsync
                recompilepkg "$@"
                ;;
        recompileallpkg)
		argentsync
		cleanoutdated
                recompileallpkg
                ;;
        autorecompileallpkg)
		argentsync
                cleanoutdated
                autorecompileallpkg
                ;;
        autorecompilepkg)
		argentsync
		cleanoutdated
                autorecompilepkg "$@"
                ;;
	autoforceremove)
		argentsync
		emerge --unmerge -v "$@"
		;;
	autoclean)
		argentsync
		emerge --depclean -q
		;;
	autoupgrade)
		argentsync
		emerge -uDvN --with-bdeps=y @system @world "$@"
		;;
	fetchsourcepkg)
		fetchsourcepkg "$@"
		;;
	search)
		emerge -s "$@"
		;;
	update)
		argentsync
		;;
	sysinfo)
		emerge --info
		;;
	*)
		cat <<-"EOH"
			Usage: epkg command [package(s)]

			epkg is a simple wrapper around portage, gentoolkit, and portage-utils that provides an
			apt-get/yum-alike interface to these commands, to assist people transitioning from
			Debian/RedHat-based systems to Gentoo.

			Commands :
				install - Install new packages
				remove - Remove packages safely
				backuppkg - Backup specific packages with own configurations for later use
				forceremove - *Unsafely* remove packages
				clean - Remove packages that are no longer needed
				cleanoutdated - Remove local saved and outdated packages
				cleanpkg - Remove all locally saved packages ( including index )
				upgrade -  Upgrade system
				autoinstall - Install new packages (no confirmation)
				autoremove - Remove packages safely (no confirmation)
				recompilepkg - Recompile packages with self-defined options ( man portage )
				recompileallpkg - Recompile and save all the packages locally ( usually in /usr/portage/packages/ )
				autorecompilepkg - Recompile packages with self-defined options ( no confirmation )
				autorecompileallpkg - Recompile and save all the packages in the system ( no confirmation )
				autoforceremove - *Unsafely* remove packages (no confirmation)
				autoclean - Remove packages that are no longer needed (no confirmation)
				autoupgrade - Upgrade system (no confirmation)
				fetchsourcepkg - Downloads the source of the program. Usually in /usr/portage/distfiles/
				search - Search for packages
				update - Resync portage tree, portage config && argent-ws overlay
				sysinfo - Display information about installed core packages and portage configuration
		EOH
		;;
esac
