#!/usr/bin/env bash

checkroot () {
	if [[ "$(whoami)" != root ]] ; then
		echo ""
		echo "You're not root?...No cookies for you, go away !!!"
		echo ""
		exit 1
	fi
}

fetch_portage_tree() {
	cd /usr/portage && git init
	git remote add origin git://anongit.gentoo.org/repo/gentoo.git
	git pull --depth=1 origin master
	git branch -u origin/master master
}

fetch_kogaion_overlay() {
	layman -f -a kogaion-desktop -o https://gitlab.com/kogaion/kogaion-desktop/raw/master/overlay.xml
}

main() {
	if checkroot; then
		fetch_portage_tree
		fetch_kogaion_overlay
	fi
}

main
