#!/usr/bin/env bash

# import gentoo functions
source /lib/gentoo/functions.sh

checkroot () {
	if [[ "$(whoami)" != root ]] ; then
		eerror "You're not root?...No cookies for you, go away !!!"
		exit 1
	fi
}

checksystemmode() {
	if [[ "$(readlink -f "/etc/portage/make.conf")" = /opt/argentws-build/conf/intel/portage/make.conf.amd64-srcmode ]] ; then
		eerror "The system is set to srcmode (full Gentoo mode), cowardly refusing to run!"
		exit 1
	fi
}

checkportageconfig () {
	pushd /opt/argentws-build > /dev/null 2>&1
	git remote update > /dev/null 2>&1
	export local confhash=$(git rev-parse @)
	export local rconfhash=$(git rev-parse @{u})
	if [ $confhash != $rconfhash ] ; then
		eerror "Portage config is out of date, run "epkg update" first"
		exit 1
	fi
	popd > /dev/null 2>&1
}

checkportagetree () {
	pushd /usr/portage > /dev/null 2>&1
	git remote update > /dev/null 2>&1
	export local treehash=$(git rev-parse @)
	export local rtreehash=$(git rev-parse @{u})
	if [ $treehash != $rtreehash ] ; then
		eerror "Portage tree is out of date, run "epkg update" first"
		exit 1
	fi
	popd > /dev/null 2>&1
}

checkargentoverlay () {
	pushd /var/lib/layman/argent-desktop > /dev/null 2>&1
	git remote update > /dev/null 2>&1
	export local overlayhash=$(git rev-parse @)
	export local roverlayhash=$(git rev-parse @{u})
	if [  $overlayhash != $roverlayhash ] ; then
		eeror "argent-ws overlay is out of date, run "epkg update" first"
		exit 1
	fi
}

checksync () {
	checkportagetree
	checkargentoverlay
	checkportageconfig
}

syncrepos () {
	emerge --sync
}

syncportageconfig () {
	pushd /opt/argentws-build > /dev/null 2>&1
	echo ">>> Syncing 'portage config' into '/etc/portage'..."
	echo "/usr/bin/git pull"
	git pull
	echo "=== Sync completed for 'portage config'"
	popd > /dev/null 2>&1
}

argentsync () {
	syncrepos
	syncportageconfig
}
